(()=>{'use strict';const app=document.querySelector('main.app');if(!app)return;
const persistentHero=app.querySelector('.mm-hero');if(persistentHero){persistentHero.classList.add('mm-persistent-hero');document.body.insertBefore(persistentHero,app)}const dashboard=document.createElement('div');dashboard.className='mm-screen mm-dashboard';dashboard.id='mm-dashboard';for(const selector of ['.mm-hero','.mm-metrics','.mm-board','.mm-bottom']){const el=app.querySelector(selector);if(el)dashboard.append(el)}
const workspace=document.createElement('div');workspace.className='mm-screen mm-workspace';workspace.id='mm-workspace';
const heading=document.createElement('div');heading.className='mm-workspace-title';heading.innerHTML='<span>OPERATIONS / WORKSPACE</span><h2 id="mm-workspace-heading">Inspections</h2><button type="button" id="mm-back-dashboard">← BACK TO DASHBOARD</button>';workspace.append(heading);
const views={};for(const name of ['Upcoming & Bad Orders','Add Inspection','Completed','Reports','Settings']){const section=document.createElement('div');section.className='mm-workspace-view';section.dataset.view=name;section.hidden=true;views[name]=section;workspace.append(section)}
const working=document.getElementById('upcomingBadOrders');const completed=document.getElementById('mm-completed')||document.getElementById('inspectionList')?.closest('section.card');const entry=app.querySelector('section.equipment-entry');const terminal=document.getElementById('terminal')?.closest('section.card');const sidebar=app.querySelector('.sidebar-stack');const notes=document.getElementById('generateEod')?.closest('section.card');const preview=document.getElementById('previewCard');
if(working)views['Upcoming & Bad Orders'].append(working);
if(sidebar)views['Add Inspection'].append(sidebar);
if(entry)views['Add Inspection'].append(entry);
if(completed)views.Completed.append(completed);
if(notes)views.Reports.append(notes);
if(preview)views.Reports.append(preview);
const settingsInfo=document.createElement('section');settingsInfo.className='card';settingsInfo.innerHTML='<div class="card-header-styled"><h2>Settings</h2></div><div class="card-body"><p>Choose your terminal from Add Inspection. Terminal settings also determine which inspections are saved and reported.</p><button type="button" id="mm-settings-terminal">OPEN TERMINAL SETTINGS</button></div>';views.Settings.append(settingsInfo);
app.replaceChildren(dashboard,workspace);
const names=['Dashboard','Upcoming & Bad Orders','Add Inspection','Completed','Reports','Settings'];const tabs=[...document.querySelectorAll('.mm-side .mm-nav')];let active='Dashboard';
function show(name){if(!names.includes(name))name='Dashboard';active=name;const home=name==='Dashboard';if(persistentHero){persistentHero.hidden=false;persistentHero.style.display='flex';}dashboard.hidden=!home;workspace.hidden=home;for(const [key,el] of Object.entries(views))el.hidden=home||key!==name;tabs.forEach((b,i)=>{b.classList.toggle('active',names[i]===name);b.setAttribute('aria-current',names[i]===name?'page':'false')});if(!home)document.getElementById('mm-workspace-heading').textContent=name;window.scrollTo({top:0,behavior:'instant'});document.documentElement.scrollTop=0;document.body.scrollTop=0}
tabs.forEach((b,i)=>b.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();show(names[i])},true));
document.getElementById('mm-back-dashboard').addEventListener('click',()=>show('Dashboard'));
document.getElementById('mm-settings-terminal').addEventListener('click',()=>{show('Add Inspection');document.getElementById('terminal')?.focus()});
document.querySelectorAll('.mm-board [data-go]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();show('Upcoming & Bad Orders');const view=button.dataset.go==='bad'?'bad':'upcoming';window.dispatchEvent(new CustomEvent('eod:report-view',{detail:view}))},true));
document.querySelectorAll('.mm-bottom [data-action]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();const action=button.dataset.action;if(action==='inspection')show('Add Inspection');else if(action==='bad'){show('Upcoming & Bad Orders');window.dispatchEvent(new CustomEvent('eod:report-view',{detail:'bad'}))}else if(action==='report')show('Reports');else show('Completed')},true));
window.addEventListener('eod:inspect-selected',event=>{const asset=String(event.detail?.asset||'').toUpperCase().replace(/[^A-Z0-9]/g,'');const match=asset.match(/^([A-Z]{4})([0-9]{5,6})$/);if(!match)return;show('Add Inspection');document.getElementById('tab-chassis')?.click();const prefix=document.getElementById('prefix');const number=document.getElementById('number');if(!prefix||!number)return;const option=[...prefix.options].find(x=>x.value===match[1]);if(option){prefix.value=match[1];prefix.dispatchEvent(new Event('change',{bubbles:true}))}else{const opt=new Option(match[1],match[1]);prefix.append(opt);prefix.value=match[1];prefix.dispatchEvent(new Event('change',{bubbles:true}))}number.value=match[2];number.dispatchEvent(new Event('input',{bubbles:true}));number.focus();});show('Dashboard');
})();